# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M9mkjAi3FKo5vS_sfKzsIXG32YnrsTQx
"""

!pip install cryptography

!pip install onnxruntime

!pip install onnx

from cryptography.fernet import Fernet

key = Fernet.generate_key()

with open('mykey.key', 'wb') as mykey:
    mykey.write(key)

with open('mykey.key', 'rb') as mykey:
    key = mykey.read()

print(key)

f = Fernet(key)

with open('/content/drive/MyDrive/onnx/yolov4.onnx', 'rb') as original_file:
    original = original_file.read()

encrypted = f.encrypt(original)

with open ('/content/s/enc_file.prisma', 'wb') as encrypted_file:
    encrypted_file.write(encrypted)

import onnx
import onnxruntime

f = Fernet(key)

with open('/content/s/enc_file.prisma', 'rb') as encrypted_file:
    encrypted = encrypted_file.read()

sess=onnxruntime.InferenceSession(encrypted)

model=onnx.load_model(encrypted)

